### ISSUE TITLE
Debug logging does not properly log to the GCP console

### ISSUE THREAD

**Issue by thefirstofthe300** [GoogleCloudPlatform/python-compat-runtime#104]
I have a very basic app and am trying to get debug logging to show in the console; however, I am only able to get debug logging to show if I add a logging handler to send the logs to stdout in addition to the log file.

app.yaml

        runtime: python-compat
        vm: true
        api_version: 1
        threadsafe: true

        handlers:
        - url: /.*
            script: main.app

main.py (doesn't write to GCP logging console)
        
        import logging
        import sys
        import webapp2

        class MainPage(webapp2.RequestHandler):
            def get(self):
                self.response.headers['Content-Type'] = 'text/plain'
                self.response.write('Hello, World!')
                logging.debug("This is a debug message")
                logging.info("this is an info message")

        app = webapp2.WSGIApplication([
            ('/', MainPage),
        ], debug=True)

main.py (does write to GCP logging console)

        import logging
        import sys
        import webapp2

        class MainPage(webapp2.RequestHandler):
            def get(self):
                self.response.headers['Content-Type'] = 'text/plain'
                self.response.write('Hello, World!')
                root = logging.getLogger()
                root.setLevel(logging.DEBUG)

                ch = logging.StreamHandler(sys.stdout)
                ch.setLevel(logging.DEBUG)
                formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
                ch.setFormatter(formatter)
                root.addHandler(ch)
                root.debug("this is a debug message")

        app = webapp2.WSGIApplication([
            ('/', MainPage),
        ], debug=True)

**Comment by jonparrott** [comment]
This is as intended. In flexible, you have to explicitly turn on logging, e.g.:

```
logging.basicConfig(level=logging.DEBUG)
```

**Comment by thefirstofthe300** [comment]
Even after adding 
        
        logging.basicConfig(level=logging.DEBUG)

I am still not able to see debug logs in the console.

main.py

       import logging
       import sys
       import webapp2

       logging.basicConfig(level=logging.DEBUG)

       class MainPage(webapp2.RequestHandler):
           def get(self):
               self.response.headers['Content-Type'] = 'text/plain'
               self.response.write('Hello, World!')
               logging.info('this is a logging info message')
               logging.debug('this is a debug message')

       app = webapp2.WSGIApplication([
           ('/', MainPage),
       ], debug=True)

**Comment by jonparrott** [comment]
Where are you looking for logs? Can you share a screenshot?

**Comment by thefirstofthe300** [comment]
I am looking under Stackdriver Logging->Logs.  The odd thing about this error is that only the debug logs are left out.  If I use the custom handler, all the logs (debug, info, etc) are piped to stdout as I would expect.  However, the debug logs then also appear in the app log.  Can you explain this behavior?  I would only expect the debug logs to show up in stdout if there is a bug preventing debug logs from being logged to the app log in the console.

The app below is using the main.py from my previous post.

![no debug log](https://cloud.githubusercontent.com/assets/3161330/18568418/00ad6730-7b52-11e6-805a-0c20fa4a4c70.png)

**Comment by jonparrott** [comment]
@andrewsg or @bryanmau1 might have some insight.

**Comment by csilvers** [comment]
Can you explain a bit more about "behaving as intended"?  I thought the goal of python-compat was to be as similar to the "normal" GAE runtime as possible.  In the normal GAE runtime, DEBUG logs are exported.  Shouldn't that be the case in python-compat, then, as well?

That is, I understand that in flexible you have to set the log level explicitly.  But I feel the "you" in this case should be the python-compat layer, which should be setting it so as to match what normal-GAE does.  Am I very confused?

**Comment by andrewsg** [comment]
Try configuring the root logger to DEBUG:

`logging.getLogger('').setLevel(logging.INFO)`

The logs should appear in the "app" stream in the logs viewer, if it is working correctly.

**Comment by csilvers** [comment]
Also, I don't think changing the loglevel in the user's app would do any good; `basicConfig` has already been called at that point. (It would probably work to grovel through the existing log handlers and modify them in place.)

I //think// the relevant code where things would need to be changed is at the top of `appengine-compat/exported_appengine_sdk/google/appengine/tools/vmboot.py`:
```
logging.basicConfig(level=logging.INFO)
```
I think just changing that to DEBUG would give GAE compatibility.

But it's possible that it's the `basicConfig` in appengine-compat/exported_appengine_sdk/google/appengine/ext/vmruntime/initialize.py.  That _seems_ to be for syslog logging, but I admit I don't really understand how all these bootstrapping files fit together.

**Comment by andrewsg** [comment]
Those bootstrapping files are just part of the SDK and not in the boostrapping path for `runtime: python-compat`. Look at wsgi.py instead. You can see how it all fits together by starting at the Dockerfile, which starts up gunicorn and loads vmruntime.wsgi:meta_app, and go from there.

**Comment by csilvers** [comment]
Ah, I see!  Thanks for the pointer.  So it looks like the `root_logger.setLevel(logging.INFO)` in wsgi.py is what should be changed to `logging.DEBUG`, at least according to how I understand the goals of the python-compat runtime.  I'm probably misunderstanding.  Can you explain why it's correct for python-compat to default to INFO-and-above level logging, given that normal GAE logs DEBUG-and-above?

**Comment by andrewsg** [comment]
Many of the internal components of the SDK that are used on the VM but are not used on GAE Standard emit DEBUG-level logs at high volumes. If you want to use DEBUG-level logs, I'd recommend trimming out specific modules using the log hierarchy.

**Comment by csilvers** [comment]
I see -- so if I understand you right, turning on DEBUG-level logging, even within our app like you suggested, will spam the app-logs with tons of logging messages from the Google framework.  I can see how that would make this feature difficult to implement.

Nevertheless, I would suggest re-opening the bug, since it does seem like a compatibility bug that application DEBUG logs do not make it to the app-log.  The idea of trimming out specific modules -- namely any of the framework modules -- makes a lot of sense, but I think the "right" approach is for the python-compat library to do that, rather than for all application authors to have to do that themselves.

**Comment by csilvers** [comment]
I've been thinking more about this.  Semantically, it seems like the right thing to use the logs hierarchy, since we consider the framework and the app to be separate "things", so it would make sense they have separate loggers.  But in practice it seems like a lot of work for one side or the other: either the framework code would have to be pretty heavily modified, or the application code, to changing all the `logging.foo` calls to use the non-root logger instead.

Another solution, which is hackier but less invasive, would be to use log filters.  In this scheme, we'd set the root logger log-level to DEBUG, but add a log filter that filters out all DEBUG messages where the log-location does not start with `/app`.  (Maybe we should filter out framework INFO messages too, by default; our app logs are kinda overwhelmed right now with `Service bridge API call to package` messages.)

Thoughts?  I could try coding this up, if you guys would be amenable to such a patch.
