### ISSUE TITLE
Endpoints unavailable after build

### ISSUE THREAD

**Issue by zeapo** [GoogleCloudPlatform/python-compat-runtime#32]
When building the runtime ourselves rather than using the docker image provided by Google, we are unable to access the endpoints.
We noticed that both `endpoints-1.0` and `protorpc` are excluded during installation https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/blob/master/setup.py#L37.

**Comment by andrewsg** [comment]
Our intention is not to vendor libraries with the runtime package but instead have them installed with pip. Both endpoints and protorpc are in PyPI, so we'd like to install them with "RUN pip install" in the Dockerfile rather than package them with the runtime.

Using the docker image provided by Google, are you able to import endpoints and protorpc by default? Or do you have to specify them for instance in the libraries section of your yaml configuration file? If they are installed by default without any specific configuration, then we'll want to add them to the Dockerfile by default (though still via pip).

**Comment by zeapo** [comment]
Sadly the Google Cloud Endpoints library is not available in PyPi, the package named `endpoints` in PyPi is not the Google one.

We use the same hack as in https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/issues/131 to use the endpoints. When doing an import from `google.appengine.ext`, then `endpoints-1.0` is added to sys.path. This works with the docker image provided by Google (gcr.io/google_appengine/python-compat).

**Comment by andrewsg** [comment]
Whoops, thank you for setting me straight there.

**Comment by jonparrott** [comment]
For the time being, endpoints is explicitly non-supported in App Engine Flex. We may add support for Endpoints in the future, but for now this bug will be closed.
